LearnTemplates/LearnTemplates/urls.py
from django.contrib import admin
from django.urls import path, include
from basicApp import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('basicApp/', include('basicApp.urls')),
]

LearnTemplates/basicApp/urls.py
from django.urls import path, include
from basicApp import views


# Template tagging
app_name = 'basicApp'

urlpatterns = [
    path('relative', views.relative, name='relative'),
    path('other', views.other, name='other'),
]

LearnTemplates/basicApp/models.py
from django.db import models

# Create your models here.

LearnTemplates/basicApp/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
    context_dict = {'text':'hello world', 'number': 100}
    return render(request, 'index.html', context_dict)

def other(request):
    return render(request, 'other.html')

def relative(request):
    return render(request, 'relative_url_temp.html')

LearnTemplates/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title></title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-light bg-light">
        <a class="navbar-brand" href="{% url "index" %}">Home</a>
        <button class="navbar-toggler d-lg-none" type="button" data-toggle="collapse" data-target="#collapsibleNavId" aria-controls="collapsibleNavId"
            aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="collapsibleNavId">
            <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url "admin:index" %}">Admin<span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url "basicApp:other" %}">Others</a>
                </li>
            </ul>
            <form class="form-inline my-2 my-lg-0">
                <input class="form-control mr-sm-2" type="text" placeholder="Search">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            </form>
        </div>
    </nav>

    <div class="container">
        {% block body_block %}

        {% endblock %}
    </div>
    
</body>
</html>

LearnTemplates/templates/index.html
<!DOCTYPE html>
{% extends "base.html" %}
{% block body_block %}
    <h1>Welcome to index!</h1>
    <h2>This is index.hmtl page showing!</h2>
    {{ text|cut:'world' }}
    {{ number }}
    {% endblock %}

LearnTemplates/templates/other.html
<!DOCTYPE html>
{% extends "base.html" %}
{% block body_block %}
    <h1>Welcome to other!</h1>
    <h2>This is an example of template inheritence!</h2>
    {% endblock %}

LearnTemplates/templates/relative_url_temp.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>RelativeURL</title>
</head>
<body>
    <h1>Welcome to relative!</h1>
    <a href="{% url 'basicApp:other' %}">The other page</a>
    <a href="{% url 'admin:index' %}">Link to admin</a>
    <a href="{% url 'index' %}">Link to index</a>
</body>
</html>